### ISSUE TITLE
String array supplied IP's don't seem to work

### ISSUE THREAD

**Issue by Miosame** [stogoh/network-mapper#8]
> The option allows either a string or string array as an argument.

The readme notes an array can be supplied as an argument for target, e.g.:

```
    const scan = new ListScan({
        target: ['192.168.1.24','192.168.1.25','192.168.1.26'],
        dnsServer: ['192.168.1.1']
    })
    const result = await scan.run()
```

however that immediately fulfills the promise with an empty result, running the same query in terminal, comma separated values indeed return nothing (what network-mapper does with string arrays), however separating the targets via space does - if I `.join(" ")` the targets before passing it to network-mapper it doesn't work either though.

**Comment by stogoh** [comment]
Indeed this was an issue. Nmap handles multiple hosts for the **host** option a bit different. Target hosts must be seperated with a space, not a comma. The approch with `.join(" ")` does also not work for me. Reason beeing how the child porccess is spawned. The used arguments are passed to the child process via an array. Apperently when there is a space in one item in the array the item gets wrapped in quotes. This results for example in `"192.168.1.24 192.168.1.25"`. Nmap then tries to resolve this as a dns name which will fail of course. Resulting in an immediately fulfills the promise

In the new release the array is no longer joined together, all the items in the array are concated to the generated argument array. This resolved this issue and it is now possible to specify multiple target hosts.
